
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Orri', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Gussi', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Maggi', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Kjartan', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Gaggi', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Jökull', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('EBÓ', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Marteinn', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Eiki', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Sturri', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Vésteinn', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Bragi', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Pétur Már', 0, 0, 0, 0, 0, 0, 0)
insert into player (name, wins, losses, draws, gamesWon, gamesLost, attented, deleted)
values ('Varamaður', 0, 0, 0, 0, 0, 0, 0)