// <auto-generated />
using System;
using API.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.EntityModels.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date");

                    b.Property<bool>("deleted");

                    b.Property<bool>("draw");

                    b.Property<string>("teamOneList");

                    b.Property<bool>("teamOneWin");

                    b.Property<string>("teamTwoList");

                    b.Property<bool>("teamTwoWin");

                    b.HasKey("ID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("API.Models.EntityModels.GameInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("draw");

                    b.Property<int>("gid");

                    b.Property<int>("pid");

                    b.Property<string>("result");

                    b.Property<bool>("teamOne");

                    b.Property<int>("teamOneScore");

                    b.Property<bool>("teamTwo");

                    b.Property<int>("teamTwoScore");

                    b.HasKey("ID");

                    b.ToTable("GamesWon");
                });

            modelBuilder.Entity("API.Models.EntityModels.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("attented");

                    b.Property<bool>("deleted");

                    b.Property<int>("draws");

                    b.Property<int>("gamesLost");

                    b.Property<int>("gamesWon");

                    b.Property<string>("lastFive");

                    b.Property<int>("losses");

                    b.Property<string>("name");

                    b.Property<int>("wins");

                    b.HasKey("ID");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
